source = ~/.config/hypr/sys.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/windows.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/tiling.conf
source = ~/.config/hypr/inputs.conf
