general {
    disable_loading_bar = true
    hide_cursor = true
}

input-field {
    monitor =

    size = 300, 30
    outline_thickness = 2
    rounding = 10

    # Colors
    inner_color = rgba(0, 0, 0, 0.40)
    outer_color = rgba(200, 200, 200, 0.90)
    font_color  = rgb(230, 230, 230)

    # Password dots
    dots_size     = 0.33
    dots_spacing  = 0.25
    dots_center   = true
    dots_rounding = -1

    # No extra text
    placeholder_text =
    fail_text =

    fade_on_empty = false

    # Center of screen
    halign = center
    valign = center
    position = 0, 0
}

