-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

require("user.bindings")
require("user.inputs")
require("user.monitors")
require("user.sys")
require("user.tiling")
require("user.windows")
