$terminal    = kitty
$browser     = chromium
$fileManager = thunar
$menu        = rofi -show drun
$mainMod     = ALT

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE
exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle

xwayland {
  force_zero_scaling = true
}
