windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
  name = tui-float
  match:class = ^org\.misha\..*$
  float = on
  center = on
  size = (monitor_w*0.7) (monitor_h*0.7)
  tag = +floating-window
}

windowrule = match:class wofi, tile on
windowrule = match:class wofi, workspace special:launcher silent
windowrule = match:class wofi, size 420 100%
windowrule = match:class wofi, move 100%-420 0
windowrule = match:class wofi, animation slide right

windowrule = match:class discord, workspace 1, no_initial_focus on
windowrule = match:class chromium, workspace 2, no_initial_focus on
windowrule = match:class YouTube Music Desktop App, workspace 4, no_initial_focus on

exec-once = [workspace 1] discord
exec-once = [workspace 2] chromium
exec-once = [workspace 3] kitty
exec-once = [workspace 4] youtube-music-desktop-app

general {
    gaps_in = 2.5
    gaps_out = 2.5
    border_size = 2
    col.active_border = rgba(9A90B8FF)
    col.inactive_border = rgba(2B2B2BFF)
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
}

decoration {
    rounding = 7
    rounding_power = 2
    active_opacity = 1.0
    inactive_opacity = 1.0
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
    blur {
        enabled = true
        size = 3
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
    bezier = fast, 0.2, 0.9, 0.2, 1.0
    animation = windows, 1, 1.0, fast, popin 85%
    animation = windowsOut, 1, 1.0, fast, popin 85%
    animation = border, 1, 1.0, fast
    animation = fade, 1, 1.0, fast
    animation = workspaces, 1, 1.0, fast, slide
}
