-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local consts = require("user.consts")
local mainMod = consts.mainMod

-- Reload / Exit
hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "E", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "N", hl.dsp.exec_cmd("~/.local/bin/launch-tui impala"))

-- Screenshot
hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("hyprshot -m window --clipboard-only"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m output --clipboard-only ```:contentReference[oaicite:0] { index=0 }"))

-- Media
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { repeating = true, locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { repeating = true, locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Launchers
hl.bind(mainMod .. " + " .. "space", hl.dsp.exec_cmd(consts.menu))
hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd(consts.terminal))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.exec_cmd(consts.fileManager))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "B", hl.dsp.exec_cmd(consts.browser))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("youtube-music-desktop-app"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "A", hl.dsp.exec_cmd("~/.local/bin/launch-webapp \"https://chatgpt.com\""))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Y", hl.dsp.exec_cmd("~/.local/bin/launch-webapp \"https://youtube.com/\""))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("discord"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("steam"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("~/.local/bin/launch-tui-tile btop"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("~/.local/bin/launch-webapp \"https://gmail.com\""))

-- Notifications
hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -t"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("swaync-client -C"))
hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("swaync-client -d"))
hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("swaync-client -D"))
