-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
  output   = "DP-1",
  mode     = "2560x1440@165",
  position = "0x0",
  scale    = "auto",
  vrr = 0,
})
