-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local consts = require("user.consts")
local mainMod = consts.mainMod

-- Kill window
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

-- Close windows
hl.bind("CTRL + ALT + DELETE", hl.dsp.exec_cmd("~/.local/bin/close-all-windows"))

-- Fullscreen
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen({ mode = 1 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "F", hl.dsp.window.fullscreen())

-- Control tiling
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "T", hl.dsp.window.float())

-- Move focus with $mainMod + arrow keys
hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with $mainMod + [1-9; 0]
hl.bind(mainMod .. " + " .. "code:10", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "code:11", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "code:12", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "code:13", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "code:14", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "code:15", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "code:16", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "code:17", hl.dsp.focus({ workspace = 8 }))

-- Move active window silently to a workspace with $mainMod + SHIFT + ALT + [1-9; 0]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 , follow = false}))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 , follow = false}))

-- Move active window to a workspace with $mainMod + SHIFT + [1-9; 0]
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:10", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:11", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:12", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:13", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:14", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:15", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:16", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "code:17", hl.dsp.window.move({ workspace = 8 }))

-- TAB between workspaces
hl.bind(mainMod .. " + " .. "TAB", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "TAB", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

-- Move workspaces to other monitors
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "LEFT", hl.dsp.workspace.move({ monitor = "l" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "RIGHT", hl.dsp.workspace.move({ monitor = "r" }))

-- Swap active window with the one next to it with $mainMod + SHIFT + arrow keys
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.swap({ direction = "left" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.swap({ direction = "right" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.swap({ direction = "up" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.swap({ direction = "down" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.layout("togglesplit"))

-- Resize Active Window
hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
  hl.bind("H", hl.dsp.window.resize({ x = -25, y = 0, relative = true }))
  hl.bind("L", hl.dsp.window.resize({ x = 25, y = 0, relative = true }))
  hl.bind("K", hl.dsp.window.resize({ x = 0, y = -25, relative = true }))
  hl.bind("J", hl.dsp.window.resize({ x = 0, y = 25, relative = true }))
  hl.bind("Return", hl.dsp.submap("reset"))
  hl.bind("Escape", hl.dsp.submap("reset"))
end)

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
