-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.window_rule({
  name  = "suppress-maximize-events",
  match = {
    class = ".*",
  },
  suppress_event = "maximize",
})

hl.window_rule({
  name  = "tui-float",
  match = {
    class = "^org\\.misha\\..*$",
  },
  float = true,
  center = true,
  size = { "(monitor_w*0.7)", "(monitor_h*0.7)" },
  tag = "+floating-window",
})

hl.window_rule({
  name  = "tile_on_16",
  match = {
    class = "wofi",
  },
  tile = true,
})

hl.window_rule({
  name  = "workspace_special_la_17",
  match = {
    class = "wofi",
  },
  workspace = "special:launcher silent",
})

hl.window_rule({
  name  = "size_420_100__18",
  match = {
    class = "wofi",
  },
  size = { 420, "100%" },
})

hl.window_rule({
  name  = "move_100_-420_0_19",
  match = {
    class = "wofi",
  },
  move = { "100%-420", 0 },
})

hl.window_rule({
  name  = "animation_slide_righ_20",
  match = {
    class = "wofi",
  },
})

hl.window_rule({
  name  = "workspace_5_22",
  match = {
    class = "^(steam_app_.*)$",
  },
  workspace = 5,
})

hl.window_rule({
  name  = "workspace_5_23",
  match = {
    class = "org.prismlauncher.PrismLauncher",
  },
  workspace = 5,
})

hl.window_rule({
  name  = "workspace_1_24",
  match = {
    class = "steam",
  },
  workspace = 1,
})

hl.window_rule({
  name  = "workspace_1_25",
  match = {
    class = "vesktop",
  },
  workspace = 1,
})

hl.window_rule({
  name  = "workspace_4_26",
  match = {
    class = "YouTube Music Desktop App",
  },
  workspace = 4,
})

hl.config({
  general = {
    gaps_in = 2.5,
    gaps_out = 2.5,
    border_size = 2,
    layout = "dwindle",
    col = {
      active_border = "rgba(9A90B8FF)",
      inactive_border = "rgba(2B2B2BFF)",
    },
  },
})

hl.config({
  dwindle = {
    preserve_split = true,
  },
})

hl.config({
  decoration = {
    rounding = 7,
    rounding_power = 2,
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    shadow = {
      enabled = true,
      range = 4,
      render_power = 3,
      color = "rgba(1a1a1aee)",
    },
    blur = {
      enabled = true,
      size = 3,
      passes = 1,
      vibrancy = 0.1696,
    },
  },
})

hl.config({
  animations = {
    enabled = true,
  },
})

hl.curve("fast", {
  type = "bezier",
  points = { { 0.2, 0.9 }, { 0.2, 1.0 } },
})

hl.animation({ leaf = "windows", enabled = true, speed = 1.0, bezier = "fast", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.0, bezier = "fast", style = "popin 85%" })
hl.animation({ leaf = "border", enabled = true, speed = 1.0, bezier = "fast" })
hl.animation({ leaf = "fade", enabled = true, speed = 1.0, bezier = "fast" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.0, bezier = "fast", style = "slide" })

-- Autostart
hl.on("hyprland.start", function()
  hl.exec_cmd("[workspace 1] vesktop")
  hl.exec_cmd("[workspace 1] steam")
  hl.exec_cmd("[workspace 2] chromium")
  hl.exec_cmd("[workspace 3] kitty")
  hl.exec_cmd("[workspace 4] youtube-music-for-desktop")
end)
