# /bin/bash
alias xilinx-launch="bash /home/mikhail/Documents/scripts/containers/launch.sh xilinx"
alias connect="bash /home/mikhail/Documents/scripts/containers/connect.sh"

alias pico="bash $HOME/Documents/scripts/util/pico.sh"
alias picov="picocom /dev/ttyUSB1 -b 115200 --omap delbs"
alias analyzer="xfreerdp /v:10.65.10.221 /u:analyzer1 /p:1553 /size:1400x900"

alias full-update="sudo $HOME/Documents/scripts/util/full_update.sh"
alias clean-sys=$HOME/.shell/clean_sys.sh
alias trash=$HOME/.shell/empty_trash.sh

alias c=clear
alias vim=nvim
alias cd=z
alias cdi=zi
alias tmux="tmux new-session -A -s main"
alias ssh="TERM=xterm ssh"
alias pic="kitty +kitten icat "
