# /bin/bash

# Runs a sequence of cleaning commands to refresh OS
alias clean_sys=$HOME/.shell/clean_sys.sh

# Empty Trash
alias trash=$HOME/.shell/empty_trash.sh

# Clear Baby Clear
alias c=clear

# Neovim
alias vim=nvim

# Show Img in Kitty
alias pic="kitty +kitten icat "

# XTERM SSH
alias ssh="TERM=xterm ssh"

# Mac Mini Server
alias mini="ssh misha@Mac-mini"

# zoxide override
alias cd=z

# zoxide interactive override
alias cdi=zi

alias branches='(PIPENV_PIPFILE=$HOME/.shell/clean_branches/Pipfile pipenv run python $HOME/.shell/clean_branches/main.py)'
