set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g history-limit 200000
set -g default-terminal "tmux-256color"
set -ag terminal-features ',xterm:RGB'
set -ag terminal-overrides ',xterm:Tc'
set -ag terminal-overrides ',xterm:Ms=\E]52;c;%p2%s\007'

set -g set-clipboard on
set -g mouse on
setw -g mode-keys vi

set -sg escape-time 0

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @catppuccin_flavor "frappe"
set -g @catppuccin_window_status_style "rounded"

set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

unbind %
unbind '"'
bind -n C-v split-window -h
bind -n C-s split-window -v
bind -n C-t new-window

bind -r [ previous-window
bind -r ] next-window
bind -n C-w kill-window
bind -n C-x kill-pane

bind -r n command-prompt -I "#W" "rename-window '%%'"

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi Escape send -X cancel

bind -T copy-mode-vi / command-prompt -i -p "/" "send -X search-forward-incremental \"%%%\""
bind -T copy-mode-vi ? command-prompt -i -p "?" "send -X search-backward-incremental \"%%%\""
bind -T copy-mode-vi n send -X search-again
bind -T copy-mode-vi N send -X search-reverse

bind -r v copy-mode

set -g allow-rename off
setw -g automatic-rename off
setw -g automatic-rename-format ""
