include ./themes/Tomorrow_Night_Bright.conf

shell_integration  no-cursor

font_family FiraMono Nerd Font
font_size 11.75
adjust_line_height 110%
background_opacity 0.85

cursor_blink_interval 0
window_padding_width 10
remember_window_size  no
initial_window_width  1400
initial_window_height 800
enable_audio_bell no

map ctrl+| launch --location=vsplit
map ctrl+- launch --location=hsplit

enabled_layouts Splits,Stack
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down
map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab

copy_on_select yes
allow_remote_control yes
hide_window_decorations yes
